//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseMvcParalax
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopSlider
    {
        public byte Id { get; set; }
        public string Image { get; set; }
        public string TopText { get; set; }
        public string MiddleText { get; set; }
        public string BottomText { get; set; }
        public byte Sort { get; set; }
        public bool Visible { get; set; }
    }
}
